In [29]:
import numpy as np
import pandas as pd

df=pd.read_csv('results.csv')
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [30]:
df_median=df['ConvertedCompYearly'].median()
print(df_median)
df_full=df.median(numeric_only=True)
print(df_full)

65000.0
ResponseId              32719.0
CompTotal              110000.0
WorkExp                     9.0
JobSatPoints_1             10.0
JobSatPoints_4              0.0
JobSatPoints_5              0.0
JobSatPoints_6             20.0
JobSatPoints_7             15.0
JobSatPoints_8             10.0
JobSatPoints_9              5.0
JobSatPoints_10             0.0
JobSatPoints_11             0.0
ConvertedCompYearly     65000.0
JobSat                      7.0
dtype: float64

In [31]:
#It describes the whole data;ad the quick over-view of the data
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

In [32]:
#count method gives how many people answered the particular question
df_count=df['ConvertedCompYearly'].count()
print(df_count)
#value count gives the particular insights
df_value=df['SurveyEase'].value_counts()
print(df_value)

23435
SurveyEase
Easy                          30071
Neither easy nor difficult    24581
Difficult                      1586
Name: count, dtype: int64

In [33]:
country_grp=df.groupby('Country')
print(country_grp) #it returns the object created and address
print('United States of America' in country_grp.groups)
country_grp.get_group('United States of America')

<pandas.api.typing.DataFrameGroupBy object at 0x114aafa70>
True

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
6,7,"I am not primarily a developer, but I write co...",35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Written...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
10,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
12,13,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Sch...,NaN,...,30.0,0.0,0.0,20.0,10.0,10.0,Appropriate in length,Easy,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65256,65257,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Bootstrapping a business;Professional developm...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65261,65262,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;Coding sessions (live or record...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65268,65269,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Apples,Bootstrapping a business;Professional developm...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Interactive tutorial;V...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65269,65270,"I am not primarily a developer, but I write co...",45-54 years old,"Employed, full-time",Remote,Apples,Professional development or self-paced learnin...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65270,65271,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Contribute to open-source projects;Bootstrappi...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# Get data for the United States
us_data = country_grp.get_group('United States of America')
# Count the occurrences of each value in the Check column
us_data['Check'].value_counts()

Check
Apples    11095
Name: count, dtype: int64

In [37]:
#To display the top country results
country_grp[['RemoteWork']].value_counts().head(5)

Country      RemoteWork
Afghanistan  Hybrid (some remote, some in-person)    17
             In-person                               13
             Remote                                  10
Albania      Hybrid (some remote, some in-person)    14
             Remote                                  14
Name: count, dtype: int64

In [38]:
#remote-work categories for each country
country_grp[['RemoteWork']].value_counts().groupby(level=0).head(5)

Country      RemoteWork
Afghanistan  Hybrid (some remote, some in-person)    17
             In-person                               13
             Remote                                  10
Albania      Hybrid (some remote, some in-person)    14
             Remote                                  14
                                                     ..
Zambia       Hybrid (some remote, some in-person)     4
             Remote                                   3
Zimbabwe     Hybrid (some remote, some in-person)     8
             Remote                                   6
             In-person                                6
Name: count, Length: 476, dtype: int64

In [47]:
#for the one particular country
ind_data=country_grp[['RemoteWork']].value_counts().loc['India']
print(ind_data)
filt=df["Country"]=="India"
data=df.loc[filt,"RemoteWork"].value_counts()
print(data)
print("this is the two methods of approching teh answer")
print("Median:",country_grp["ConvertedCompYearly"].median().head(5))

RemoteWork
Hybrid (some remote, some in-person)    1196
In-person                               1088
Remote                                   853
Name: count, dtype: int64
RemoteWork
Hybrid (some remote, some in-person)    1196
In-person                               1088
Remote                                   853
Name: count, dtype: int64
this is the two methods of approching teh answer
Median: Country
Afghanistan      3438.0
Albania         35341.0
Algeria          7120.0
Andorra        123517.0
Angola           1754.0
Name: ConvertedCompYearly, dtype: float64

In [53]:
#aggregator functions
agg_fun=country_grp["ConvertedCompYearly"].agg(['mean','median','sum'])
print(agg_fun.head(5))
co_agg=country_grp["ConvertedCompYearly"].agg(['mean','median']).loc['India']
print("The mean & median of the India is:\n",co_agg)

                      mean    median       sum
Country
Afghanistan    5057.250000    3438.0   60687.0
Albania       39207.545455   35341.0  431283.0
Algeria       91836.700000    7120.0  918367.0
Andorra      123517.000000  123517.0  247034.0
Angola         1366.333333    1754.0    4099.0
The mean & median of the India is:
 mean      30513.611379
median    16749.000000
Name: India, dtype: float64

In [56]:
#combining the functions
print("people learnt coding from Books method as there source is in each country is:")
print(country_grp["LearnCode"].apply(lambda x:x.str.contains("Books").sum()))
print("people learnt coding from Books method as there source in India is:")
print(country_grp["LearnCode"].apply(lambda x:x.str.contains("Books").sum()).loc['India'])

people learnt coding from Books method as there source is in each country is:
Country
Afghanistan                              24
Albania                                  14
Algeria                                  24
Andorra                                   6
Angola                                   11
                                       ...
Venezuela, Bolivarian Republic of...     36
Viet Nam                                145
Yemen                                     7
Zambia                                    9
Zimbabwe                                 18
Name: LearnCode, Length: 185, dtype: int64
people learnt coding from Books method as there source in India is:
1680